#!/usr/bin/env sh

#ADD repos and keys
if ! test -n "$(command -v google-chrome-stable)"; then
  wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
fi

if ! test -n "$(command -v dropbox)"; then
  apt-key adv --keyserver pgp.mit.edu --recv-keys 5044912E
  sh -c 'echo "deb http://linux.dropbox.com/ubuntu/ vivid main" >> /etc/apt/sources.list.d/dropbox.list'
fi

if ! test -n "$(command -v spotify)"; then
  apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D2C19886
  sh -c 'echo "deb http://repository.spotify.com stable non-free" >> /etc/apt/sources.list.d/spotify.list'
fi

#ADD PPA's

apt-get update

PKGS="
 git
 terminator
 vim-gnome
 google-chrome-stable
 dropbox
 spotify-client
 dfc
 htop
 ack-grep
 curl
 tree
"
DEV_PKGS="
 golang
 npm
"
apt-get install -y $PKGS $DEV_PKGS

if ! test -n "$(command -v rbenv)"; then
  echo "Install rbenv"
  git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
  curl https://raw.githubusercontent.com/fesplugas/rbenv-installer/master/bin/rbenv-installer | bash
fi
