#!/usr/bin/env sh

cp -a . $HOME

if [ ! -d "/usr/share/icons/Moka/" ]; then
  sudo add-apt-repository ppa:moka/stable
fi

#ADD PPA's

sudo apt-get update

PKGS="
 git
 terminator
 vim-gnome
 dropbox
 htop
 ack-grep
 curl
 tree
 moka-icon-theme
 trash-cli
 python-pip
 direnv
 xclip
 silversearcher-ag
"
DEV_PKGS="
 golang
 npm
"
sudo apt-get install -y $PKGS $DEV_PKGS

if ! test -n "$(command -v rbenv)"; then
  echo "Install rbenv"
  git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
  curl https://raw.githubusercontent.com/fesplugas/rbenv-installer/master/bin/rbenv-installer | bash
fi

# TODO: check for gnome and load config
#dconf load /org/gnome/ < dconf/org.gnome

echo "DONE!"
